### ISSUE TITLE
Add Surpass Config Files

### ISSUE THREAD

**Issue by nmfzone** [SUKOHI/Surpass#11]
It would be nice if Surpass has a config file. Hope it will be realize it soon.
Because maybe in some way i need to change the table name, etc.

Thanks.

**Comment by SUKOHI** [comment]
Thank you ,nmfzone.
Sounds nice. :)
By the way, what kind of configurations do you want except table name?
If I can, I will add them to the package.

**Comment by nmfzone** [comment]
Another features, but not configurations, i need some way to dynamically added an extra column, so i can also save the extra column when saving the images.
Ok, i believe you can add it :laughing:

**Comment by SUKOHI** [comment]
Hi, nmfzone.
I've just added feature for configuration.
Please see `Configuration` in README.md for the details.

For adding extra columns, I think we should deal with it through migration because of stable DB design.
However, thank you for your precious idea. :)

And I added your name in README.md as a contributor.
If you mind it, please inform me of it. I will remove it for sure.

Thank you!
